"""カラーパレット（ダークテーマ）。"""

# 背景色
DARK_BG_PRIMARY = "#1E1E1E"
DARK_BG_SECONDARY = "#2E2E2E"
DARK_BG_TERTIARY = "#3E3E3E"

# ボーダー色
BORDER_COLOR = "#4A4A4A"
BORDER_COLOR_LIGHT = "#5A5A5A"

# テキスト色
TEXT_PRIMARY = "#FFFFFF"
TEXT_SECONDARY = "#B0B0B0"
TEXT_MUTED = "#808080"

# アクセントカラー
ACCENT_PRIMARY = "#4A90D9"
ACCENT_SECONDARY = "#3A7BC8"
ACCENT_HOVER = "#5AA0E9"

# 状態色
SUCCESS_COLOR = "#4CAF50"
WARNING_COLOR = "#FF9800"
ERROR_COLOR = "#F44336"

# お気に入り
FAVORITE_COLOR = "#FFD700"
FAVORITE_INACTIVE = "#606060"

# カード色
CARD_BG = DARK_BG_SECONDARY
CARD_HOVER_BG = DARK_BG_TERTIARY

# サイドバー色
SIDEBAR_BG = DARK_BG_PRIMARY
SIDEBAR_ITEM_HOVER = DARK_BG_TERTIARY
SIDEBAR_ITEM_SELECTED = ACCENT_PRIMARY